#CALCULAR EL AREA DE UN CUADRADO

#PABLO ANDRES BARRETO MONTERROSA
#15/03/2022

'''Bs = int(input("1.) INGRESE LA BASE DEL CUADRADO: "))
Al = int(input("2.) INGRESE LA ALTURA CUADRADO: "))

def CalculaArea (Bs,Al):
    
    Area = Bs * Al
    return Area
    
ValorArea = CalculaArea(Bs,Al)
print("EL VALOR DEL AREA ES: ",ValorArea)'''

#============================================================

'''Valor_01 = int(input("ingresa :"))

def Descuento (Valor_01):

    Vdescuento = Valor_01 * 0.1
    return Vdescuento
    print(Vdescuento)


ValorDescuento = Descuento (Valor_01)

print(ValorDescuento)

#============================================================

def NumPrimo (NumP):
    for n in range(2,NumP):
        if NumP % n == 0:
            print(NumP,"NO es primo",n,"es el divisor")
            return False
    print("Es primo")
    return True'''


def RegUser ():

    print()
    user = input("INGRESAR USUARIO: ")
    print()
    passw = input("INGRESAR CONTRASEÑA: ")

